### ISSUE TITLE
Login with google

### ISSUE THREAD

**Issue by ProOne48** [ProOne48/spacIOs-api#2]
## User Story

As a space owner i want to be able to log in using my Google account
The user should be able to log in using the google account  they have an a user shoukd be created in the database.

### Explanation

The login is need to know who is who and be able to distinct between the space owners. I choose log in with Google because then i don't need to manage security of their passwords.

## Sub-tasks

- [x] Get authorization of google.
- [x] Save user in database.
- [x] Set cookie.
- [x] Be able to logout of google.

## Acceptance Criteria

- [x] There exist a Google Button to log in.
- [x] When logged with Google the back will verify if it's valid. Then it would set a cookie.
- [x] If the user is not in the database it would be created with Google data and an email would be send to the email to activate the account.
- [x] If the user is valid and it's account it's activated he would go in to it's personal page.

**Comment by ProOne48** [comment]
As a User i want to be able to log in using my Google account
