### ISSUE TITLE
List of all spaces in a city

### ISSUE THREAD

**Issue by ProOne48** [ProOne48/spacIOs-api#5]
## As a visitor i should be able to see a list with all the spaces there are in a city.

This should be a list with the different spaces gym, restaurants, library,... in which would appear the spaces corresponding to it's types so the visitor can select the space he wants to see.

## Sub-Tasks

- [x] Add basic information to each space listed
- [x] Links to the space for more information.
- [ ] Add sort for characteristics.

## Acceptance criteria

- [x] Each space in the list show basic data of the space(name, location,...)
- [ ] There is a menu with the options to sort.
- [x] If there is no spaces in the criteria a message appear telling warning that.
