### ISSUE TITLE
Register a new space

### ISSUE THREAD

**Issue by ProOne48** [ProOne48/spacIOs-api#6]
## User Story

As an space owner i should be able to register a new space.
An owner of an space should be able to register with a name and their characteristics (max capacity inside and outside).

### Explanation

The space owner must be able to register spaces at it's name so he can use them and the visitors can use it.

## Sub-Tasks

- [x] Get data of the space.
- [x] Check if data is correct.
- [x] Notify is something is wrong.
- [x] Create space and save in database.

## Acceptance Criteria

- [x] Exists a button to add a new space.
- [x] A form is completed with at least the basic information of the space, despite it can be fullfilled with all the data needed.
- [x] If data is valid the space it's created with the data in the form and linked to the user.
